number1 = int(input("please choose a number:"))
number2 = int(input("please choose a number:"))
number3 = int(input("please choose a number:"))
print(number1 + number2 + number3)
print(number1 - number2 - number3)
print(number1 * number2 * number3)
print(number1 / number2 / number3)